### PR TITLE
Update RGBLCD module

### PR DESCRIPTION
**Pull request by axelclark**
WORK IN PROGRESS.  Will probably be very busy at work through Sept, but figured I'd show you what I have so far.

I'm working to update the RGBLCD module using a C++ library and the datasheet.

References
* datasheet: https://www.sparkfun.com/datasheets/LCD/HD44780.pdf
* C++ library: https://github.com/Seeed-Studio/Grove_LCD_RGB_Backlight

Most of the functions work.  Use `GrovePi.RGBLCD.start` to initialize.  

There is a bug in the `GrovePi.RGBLCD.blink_on`, `GrovePi.RGBLCD.blink_off`, `GrovePi.RGBLCD.cursor_blink_on`, and `GrovePi.RGBLCD.blink_off` I have not been able to figure out.  These commands work within the `GrovePi.RGBLCD.start`function, but don't work on their own.  

I don't think `GrovePi.RGBLCD.autoscroll` works.

Also updated the home weather with new RGBLCD functions.

### CODE REVIEW

**Comment by adkron** [comment]
This is looking really good so far. Thank you for all the work you are putting into it. I don't have the stuff to test this right now, but I'm looking forward to trying it out.

**Comment by axelclark** [comment]
I figured out the bugs, so all of the functions are working now.  I created a file to demonstrate the functionality.  It is currently at `lib/grovepi/rgblcd/examples.ex`.  I'm happy to delete it or move it depending on where you think it would fit best.  I used the examples to make sure the updates work with hardware, but I don't have any automated tests at this point.

This is the biggest update I've made to a library so any suggestions for improvement are welcome.

**Comment by adkron** [comment]
@axelclark, I haven't had the time to check this, but it is looking good. I think that moving the examples module to `/examples/rgblcd.ex` or somewhere under that `examples` directory would be a good place to move it. I'm excited to play with this tonight.

**Comment by axelclark** [comment]
I moved the demo functions out into an example project.  Let me know what else you'd like me to update.  No rush, I know you are enjoying ElixirConf!!

**Comment by adkron** [comment]
Wish you were here so we could catch up. Next time!

Amos King
Binary Noggin

**Comment by adkron** [comment]
This looks good. I spent some time playing with it this morning. I'm going to mash it and do a new release. Thanks, @axelclark.

🤖 ❤️

**Pull request merged**
